import { Movie } from './movie';

export const MOVIES: Movie[] = [
    { id: 1, name: 'the Amazing Spider-Man 2', director: 'Marc Webb', year: 2014 , gender: 'Superherois', score: 10, img: 'assets/images/tas2.jpg', sinopsis:'La aparición de un nuevo y poderoso villano y el regreso de un viejo amigo provoca que Peter Parker crea que todos sus enemigos tienen una sola cosa en común: Oscorp.',video:'http://localhost:3000/videos/tas2.mp4'},
    { id: 2, name: 'star Wars EP III', director: 'George Lucas', year: 2005 , gender: 'Ciència ficció', score: 10, img: 'assets/images/sw3.jpg', sinopsis:'Seducido por el lado oscuro, Anakin Skywalker se rebela contra su mentor, Obi-Wan Kenobi, y se convierte en Darth Vader.',video:'http://localhost:3000/videos/sw3.mp4'},
    { id: 3, name: 'blade Runner 2049', director: 'Denis Villeneuve', year: 2017 , gender: 'Ciència ficció', score: 10, img: 'assets/images/br2049.jpg', sinopsis:'En el año 2049 el oficial K, un nuevo replicante de la policía de Los Ángeles, emprende la búsqueda del replicante Rick Deckard, desaparecido 30 años antes. K piensa que en Deckard reside la clave que podría permitir salvar a la sociedad del caos en el que está inmersa.',video:'./assets/videos/br2049.mp4'},
    { id: 4, name: 'batman The Dark Knight', director: 'Christopher Nolan', year: 2008, gender: 'Superherois', score: 10,  img: 'assets/images/batman.jpg', sinopsis:'Batman tiene que mantener el equilibrio entre el heroísmo y el vigilantismo para pelear contra un vil criminal conocido como el Joker, que pretende sumir Gotham City en la anarquía.',video:'./assets/videos/batman.mp4'},
    { id: 5, name: 'matrix', director: 'Lana Wachowski', year: 1999, gender: 'Ciència ficció', score: 10, img: 'assets/images/matrix.jpg', sinopsis:'Un experto en ordenadores descubre que su mundo es una simulación computarizada creada por malvada ciberinteligencia.',video:'./assets/videos/matrix.mp4'},
    { id: 6, name: 'rogue One', director: 'Gareth Edwards', year: 2016, gender: 'Ciència ficció', score: 10, img: 'assets/images/ro.jpg', sinopsis:'El Imperio va a construir una estación espacial capaz de destruir planetas, conocida como la Estrella de la Muerte. Los rebeldes, conocedores de esto, se embarcan en una misión extraordinaria: robar los planos y sabotear la estación.',video:'./assets/videos/ro.mp4'},
    { id: 7, name: 'star Wars EP II', director: 'George Lucas', year: 2002, gender: 'Ciència ficció', score: 10, img: 'assets/images/sw2.jpg', sinopsis:'En el Senado Galáctico reina la inquietud. Varios miles de sistemas solares han declarado su intención de abandonar la República. La reina Amidala regresa al Senado para conseguir un ejército que ayude a los caballeros jedi.',video:'./assets/videos/sw2.mp4'},
    { id: 8, name: 'star Wars EP I', director: 'George Lucas', year: 1999, gender: 'Ciència ficció', score: 10, img: 'assets/images/sw1.jpg', sinopsis:'Obi-Wan Kenobi es un joven aprendiz caballero Jedi bajo la tutela de Qui-Gon Jinn; Anakin Skywalker, quien después será padre de Luke Skywalker y se convertirá en Darth Vader, solamente es un niño de 9 años. Cuando la Federación de Comercio corta todas las rutas al planeta Naboo, Qui-Gon y Obi-Wan son asignados para solucionar el problema.',video:'./assets/videos/sw1.mp4'},
    { id: 9, name: 'aquaman', director: 'James Wan', year: 2018, gender: 'Superherois', score: 10, img: 'assets/images/aquaman.jpg', sinopsis:'Aquaman debe recuperar el legendario Tridente de Atlan para salvar a la ciudad subacuática de Atlantis, y al mundo de la superficie, de su hermano hambriento de poder.',video:'./assets/videos/aquaman.mp4'},
    { id: 10, name: 'spider-Man 1', director: 'Sam Raimi', year: 2002, gender: 'Superherois', score: 10, img: 'assets/images/sp1.jpg', sinopsis:'Un tímido estudiante se vuelve en un luchador contra el crimen, desde que la picadura de una araña mutante le da poderes extraordinarios.',video:'./assets/videos/sp1.mp4'}
  ];